### ISSUE TITLE
请问如何使用order by

### ISSUE THREAD

**Issue by lxhj** [MZ-Dlovely/dlovely-mysql#1]

**Comment by MZ-Dlovely** [comment]
好问题，我还没做这个功能，目前可先使用导出的connection运行自定义sql

**Comment by lxhj** [comment]
谢谢回复，
`let order = ["+age", "-name"]
const sql: String = mysql.find("abc").select(false, 'name', 'age').order(...order)
    .where({
        name: {
            val: 'Dlovely'
        },
        min: 22,
        max: 24,
        "&age": "20"
    }).SQL`

result:sql:SELECT name,age FROM abc WHERE name='Dlovely' OR min=22 OR max=24 AND age='20' ORDER BY age ASC,name DESC

可以关单了，非常感谢，顺便建议能加入leftJoin就完美了

**Comment by MZ-Dlovely** [comment]
非常感谢您的意见
然后可以看一下最新的代码，对order传入的参数做了个小修改，用&来表示逆序
[feat✨: 完善了order by指令及说明](https://github.com/MZ-Dlovely/dlovely-mysql/pull/2)
